### ISSUE TITLE
Erros messages suddenly showing on top of page.

### ISSUE THREAD

**Issue by designinjapan** [cognidox/WordBridge#70]
Everything was working fine for almost two months since we installed the wonderful wordbridge and was actually considering upgrading to the Pro version.

Today, and suddenly we are getting a long list of error messages on top of our page like the following:
Warning: DOMDocument::loadXML(): Opening and ending tag mismatch: p line 27 and td in Entity, line: 42 in /home/smis/public_html/components/com_wordbridge/helpers/helper.php on line 95

Warning: DOMDocument::loadXML(): Opening and ending tag mismatch: p line 45 and td in Entity, line: 60 in /home/smis/public_html/components/com_wordbridge/helpers/helper.php on line 95

What is that? and how can we solve it?  I tried to remove and reinstall the plugins and extensions on both sides (joomla and wordpress) but that didn't help.

Your help is much appreciated.

Thank you.

**Comment by vittala** [comment]
Hi - as you've closed the issue, I take it that the problem is now resolved?

If you're getting these errors, it would suggest to me that the RSS feed URL for the blog is no longer responding with valid XML, but is instead returning a HTML error page.

Regards
Vittal

**Comment by designinjapan** [comment]
Thank you Vittal.

Well, it seems as if it has been resolved after I reinstalled the plugins
again.  Just in case that happens again, how do I go around to solve it?

Thank you very much for your support.

On 2 December 2015 at 18:43, Vittal Aithal <notifications@github.com> wrote:

> Hi - as you've closed the issue, I take it that the problem is now
> resolved?
>
> If you're getting these errors, it would suggest to me that the RSS feed
> URL for the blog is no longer responding with valid XML, but is instead
> returning a HTML error page.
>
> Regards
> Vittal
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cognidox/WordBridge/issues/70#issuecomment-161240045>.
>



-- 
*Ahmed A. Aljonaid*
*ICT Director*

*St. Michael's International School*
Kobe, Japan
Tel: +81 (0) 78-231-8885
www.smis.org

*Growing, Working, Learning Together*

**Comment by vittala** [comment]
Hi Ahmed

Without knowing the root cause of the problem, it's not possible to say how to resolve it. However, I would generally recommend you clear the WordBridge cache (by setting the "Cache Timeout" for the blog to a small value such as 1). This will ensure that any invalid pages that were returned from WordPress will be removed from the cache.

Deleting and then re-creating the WordBridge menu item should also resolve many issues.

Regards
Vittal
